server:
  port: 8888
  servlet:
    context-path: /HF21

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/sd27?useSSL=true&useUnicode=true&characterEncoding=UTF-8


# mybatis-plus config
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false
  type-aliases-package: HF21.bean


